import os
import re
from textwrap import dedent

from fabric.decorators import task


@task
def update_django_dockerfile():
    '''
    Updates the web/Dockerfile with specific python packages so it can be
    cached during build
    '''
    packages = open('requirements.txt').readlines()

    p = []
    for package in packages:
        if package.startswith('-e '):
            p.append(package[3:])
        else:
            p.append(package)
    packages = p

    # Strip the comment after the package generated by pip-compile
    packages = [re.sub(' +# via .*$', '', a) for a in packages]

    # Whitespace is the devil
    packages = [a.strip() for a in packages]

    # Don't include comments
    packages = [a for a in packages if not a.startswith('#')]

    # Don't include local wheels
    packages = [a for a in packages if not a.startswith('.')]

    packages = ' '.join(packages)

    dockerfile_content = dedent('''
    FROM runrem_django_base

    RUN pip3 install {packages}
    '''.format(**locals()))

    open('docker/django/Dockerfile', 'w').write(dockerfile_content)

    print(dockerfile_content)
