# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('apikey', models.TextField()),
                ('host', models.TextField()),
                ('user', models.TextField()),
                ('directory', models.TextField()),
                ('command', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitbucketRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('apikey', models.TextField()),
                ('host', models.TextField()),
                ('user', models.TextField()),
                ('directory', models.TextField()),
                ('command', models.TextField()),
                ('repository', models.TextField()),
                ('branch', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
