# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractRun',
            fields=[
                ('endpoint', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('apikey', models.CharField(default=web.models.new_shortuuid, max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('directory', models.CharField(max_length=1000)),
                ('command', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BasicRun',
            fields=[
                ('abstractrun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.AbstractRun')),
            ],
            bases=('web.abstractrun',),
        ),
        migrations.CreateModel(
            name='BitbucketRun',
            fields=[
                ('abstractrun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.AbstractRun')),
                ('repository', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
            bases=('web.abstractrun',),
        ),
    ]
