# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrun',
            name='apikey',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basicrun',
            name='command',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='basicrun',
            name='directory',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='basicrun',
            name='endpoint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basicrun',
            name='host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basicrun',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='apikey',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='command',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='directory',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='endpoint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='repository',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
