# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20151120_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrun',
            name='apikey',
            field=models.CharField(default=web.models.new_shortuuid, max_length=100),
        ),
        migrations.AlterField(
            model_name='basicrun',
            name='endpoint',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='apikey',
            field=models.CharField(default=web.models.new_shortuuid, max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbucketrun',
            name='endpoint',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
