
FROM runrem_django_base

RUN pip3 install git+https://github.com/carljm/django-model-utils.git@8fb1e569756641fc773dcfd11b7963087ee5b685#egg=django-model-utils amqp==1.4.7 anyjson==0.3.3 billiard==3.3.0.21 celery==3.1.19 click==5.1 decorator==4.0.4 django==1.9rc1 djangorestframework==3.3.1 docker-compose==1.5.1 docker-py==1.5.0 dockerpty==0.3.4 docopt==0.6.2 ecdsa==0.13 fabric==1.10.2 first==2.0.1 httpie==0.9.2 ipython-genutils==0.1.0 ipython==4.0.0 jsonschema==2.5.1 kombu==3.0.29 paramiko==1.16.0 path.py==8.1.2 pexpect==4.0.1 pickleshare==0.5 pip-tools==1.1.6 ptyprocess==0.5 pycrypto==2.6.1 pygments==2.0.2 pytz==2015.7 pyyaml==3.11 redis==2.10.5 requests==2.7.0 shortuuid==0.4.2 simplegeneric==0.8.1 six==1.10.0 texttable==0.8.4 traitlets==4.0.0 websocket-client==0.34.0
